name: ???
root: ???
mode: ???
data_path: data/${dataset.root}/
num_points: 8192
num_planes: 20
num_renderings: 24

input_points_path: ${dataset.input_points_path_map.${dataset.mode}}
input_points_path_map:
  mixed: data/${dataset.root}/pc
  easy: data/${dataset.root}/eval/pc_easy
  medium: data/${dataset.root}/eval/pc_medium
  hard: data/${dataset.root}/eval/pc_hard
  
complete_points_path: data/${dataset.root}/gt
complete_planes_path: data/${dataset.root}/gt_plane
bs: ???
subset: ???
