# Default configuration for the Project.
# Values shall be overriden by respective dataset configurations.

# default settings
defaults:
  - _self_
  - dataset: abc
  - model: paco
  - override hydra/job_logging: custom
  - override hydra/hydra_logging: colorlog

# general settings
use_gpu: true
distributed: false
world_size: ???
launcher: pytorch
num_workers: 4
seed: 0
deterministic: false
sync_bn: false

# experiment settings
exp_name: default
val_freq: 1
resume_last: false
resume_from: null
debug: false

# paths
log_name: ${model.name}
output_dir: ./output/${exp_name}
tensorboard_dir: ${output_dir}/tensorboard/
reconstruction_dir: ${output_dir}/reconstructed/
reference_dir: ${dataset.data_path}/eval/ref_obj
csv_path: ${output_dir}/evaluation.csv
checkpoint_path: ./ckpt/ckpt-best.pth
checkpoint_url: https://onedrive.live.com/download?resid=12DDEE393E8C94C7!62321&authkey=!AO-2chkMvBmbQ-k
dataset_url: https://onedrive.live.com/download?resid=12DDEE393E8C94C7!62512&authkey=!AEikOHAvUCFN474&e=4W7OrD

# optimizer settings
optimizer: 
  type: AdamW
  kwargs:
    lr : 0.0001
    weight_decay : 0.0005

# scheduler settings
scheduler:
  type: LambdaLR
  kwargs:
    decay_step: 21
    lr_decay: 0.9
    lowest_decay: 0.02  # min lr = lowest_decay * lr

# batch norm scheduler
bnmscheduler:
  type: Lambda
  kwargs:
    decay_step: 21
    bn_decay: 0.5
    bn_momentum: 0.9
    lowest_decay: 0.01

# training settings
total_bs : 80
step_per_update : 1
max_epoch : 600

# loss settings
loss:
  non_obj_class_loss_weight: 0.4
  repulsion_loss_weight: 2
  plane_chamfer_loss_weight: 20
  chamfer_norm2_loss_weight: 20
  plane_normal_loss_weight: 1
consider_metric: total_loss

# evaluation settings
evaluate:
  keep_vg: false
  num_samples: 10000
  time_out: 300
  solver: "SCIP"
  single_file_path: null

# hydra settings
hydra:
  run:
    dir: ${output_dir}
  verbose: false
